### ISSUE TITLE
사파리를 제외한 앱(크롬 등)에서 공유하기를 눌렀을 때 북마크가 저장되지 않는 오류

### ISSUE THREAD

**Issue by sejinxjung** [ProjectInTheClass/SwitchingApp#44]
사파리를 제외한 앱(크롬 등)에서 공유하기를 눌렀을 때 북마크가 저장되지 않음
breakpoint를 걸어 확인을 했을 때 attachment의 값이 없어 75번 for문을 제대로 돌지 않음

해당 shareViewController 코드
<img width="887" alt="Screen Shot 2020-11-26 at 10 45 39 PM" src="https://user-images.githubusercontent.com/57951295/100358881-2318db00-303a-11eb-96f3-ec20e77e7269.png">

chrome에서 bookmarkShareExtension을 실행했을 때.
<img width="431" alt="Screen Shot 2020-11-26 at 11 07 29 PM" src="https://user-images.githubusercontent.com/57951295/100361070-1053d580-303d-11eb-9cf2-4ae2afbc5084.png">

safari에서 bookmarkShareExtension을 실행했을 때. (정상작동)
<img width="432" alt="Screen Shot 2020-11-26 at 10 56 58 PM" src="https://user-images.githubusercontent.com/57951295/100361086-134ec600-303d-11eb-92fa-516dd3104a32.png">

**Comment by Kihoon0716** [comment]
c28876d
